export const MARKETPLACE_CATEGORIES: Record<string, string[]> = {
  'Electronics & Tech': [
    'Mobile Phones & Accessories',
    'Laptops & Computers',
    'Tablets & E-Readers',
    'Cameras & Photography',
    'TVs & Home Audio',
    'Gaming & Consoles',
    'Smart Watches & Wearables',
    'Drones',
    'Cables, Chargers & Adapters',
    'Networking & WiFi',
    'Printers & Scanners',
    'Computer Components',
    'Other Electronics'
  ],
  'Home & Living': [
    'Furniture',
    'Sofas & Armchairs',
    'Beds & Mattresses',
    'Tables & Desks',
    'Storage & Shelving',
    'Kitchen Appliances',
    'Home Decor',
    'Lighting',
    'Rugs & Carpets',
    'Curtains & Blinds',
    'Bedding & Linens',
    'Cookware & Dining',
    'Cleaning Equipment',
    'Other Home Items'
  ],
  'Fashion & Accessories': [
    "Women's Clothing",
    "Men's Clothing",
    'Kids Clothing',
    'Shoes & Footwear',
    'Bags & Handbags',
    'Wallets & Purses',
    'Jewellery',
    'Watches',
    'Sunglasses & Eyewear',
    'Hats, Scarves & Gloves',
    'Belts',
    'Vintage & Retro Fashion',
    'Other Fashion'
  ],
  'Baby, Kids & Toys': [
    'Prams & Pushchairs',
    'Car Seats',
    'Cots & Nursery Furniture',
    'Baby Monitors',
    'Baby Carriers',
    'High Chairs',
    'Baby Clothing',
    'Toys & Games',
    'Lego & Building Blocks',
    'Board Games & Puzzles',
    'Dolls & Action Figures',
    'Outdoor Play Equipment',
    'Kids Bikes & Scooters',
    'School Supplies',
    'Other Baby & Kids'
  ],
  'Sports, Leisure & Hobbies': [
    'Bicycles & Cycling',
    'Fishing Equipment',
    'Camping & Hiking',
    'Fitness Equipment',
    'Gym Gear',
    'Football & Soccer',
    'GAA Gear',
    'Rugby',
    'Golf',
    'Tennis & Racket Sports',
    'Water Sports',
    'Musical Instruments',
    'Art & Craft Supplies',
    'Collectibles',
    'Model Kits',
    'Trading Cards',
    'Other Hobbies'
  ],
  'Books, Music & Movies': [
    'Books',
    'Textbooks',
    'Comics & Graphic Novels',
    'Vinyl Records',
    'CDs',
    'DVDs & Blu-rays',
    'Video Games',
    'Musical Scores & Sheet Music',
    'Magazines',
    'Other Media'
  ],
  'Garden & DIY': [
    'Garden Tools',
    'Lawnmowers',
    'Garden Furniture',
    'Plants & Seeds',
    'Pots & Planters',
    'BBQs & Outdoor Cooking',
    'Power Tools',
    'Hand Tools',
    'Building Materials',
    'Paint & Decorating',
    'Plumbing Supplies',
    'Electrical Supplies',
    'Ladders & Scaffolding',
    'Other Garden & DIY'
  ],
  'Health & Beauty': [
    'Skincare',
    'Haircare',
    'Makeup & Cosmetics',
    'Fragrances',
    'Nail Care',
    'Bath & Body',
    'Hair Dryers & Stylers',
    'Shaving & Grooming',
    'Health Monitors',
    'Vitamins & Supplements',
    'Massage & Relaxation',
    'Other Health & Beauty'
  ],
  'Business & Industrial': [
    'Office Furniture',
    'Office Equipment',
    'Shop Fittings',
    'Retail Displays',
    'Industrial Tools',
    'Safety Equipment',
    'Packaging & Shipping Supplies',
    'Catering Equipment',
    'Salon Equipment',
    'Other Business Items'
  ],
  'Pets': [
    'Pet Food',
    'Pet Toys',
    'Pet Beds & Furniture',
    'Pet Carriers & Travel',
    'Collars, Leads & Harnesses',
    'Aquariums & Fish Tanks',
    'Bird Cages & Accessories',
    'Reptile Supplies',
    'Grooming Supplies',
    'Other Pet Supplies'
  ],
  'Music & Instruments': [
    'Guitars',
    'Keyboards & Pianos',
    'Drums & Percussion',
    'Brass & Woodwind',
    'DJ Equipment',
    'PA Systems',
    'Amplifiers',
    'Effects Pedals',
    'Microphones',
    'Studio Equipment',
    'Sheet Music & Accessories',
    'Other Instruments'
  ],
  'Antiques & Collectibles': [
    'Antique Furniture',
    'Antique Jewellery',
    'Vintage Watches',
    'Stamps & Coins',
    'Art & Paintings',
    'Ceramics & Pottery',
    'Glassware',
    'Silver & Metalware',
    'Militaria',
    'Vintage Toys',
    'Sports Memorabilia',
    'Other Collectibles'
  ],
  'Wedding & Events': [
    'Wedding Dresses',
    'Bridesmaid Dresses',
    'Suits & Formal Wear',
    'Wedding Decorations',
    'Table Settings',
    'Event Furniture Hire',
    'Party Supplies',
    'Photobooth Props',
    'Other Wedding Items'
  ],
  'Other & Miscellaneous': [
    'Free Stuff',
    'Wanted Ads',
    'Swap or Trade',
    'Car Boot Sale Items',
    'Job Lots & Wholesale',
    'Lost & Found',
    'Other'
  ]
};

export const CATEGORY_NAMES = Object.keys(MARKETPLACE_CATEGORIES);
